server:
  port: 5000

spring:
    datasource:
#      url: jdbc:h2:file:/data/demo
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: admin
      password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
    h2:
      console.enabled: true